from AtividadeDeHeranca import Cliente, Alimento, Bebida, Higiene, Limpeza
C = Cliente()
C.cadastrar()
print(C)
A = Alimento()
A.cadastrar_alimento()
print(A)
B = Bebida()
B.cadastrar_bebida()
print(B)
H = Higiene()
H.cadastrar_higiene()
print(H)
L = Limpeza()
L.cadastrar_limpeza()
print(L)
